### ISSUE TITLE
Undefined function or variable 'rtenslearn_c'。

### ISSUE THREAD

**Issue by Feesics** [iN1k1/DCIA_Person_Re-Identification_Reranking#2]
Thanks for your code, and I run it occured the error----Undefined function or variable 'rtenslearn_c'。Can you tell me how to solve it?

**Comment by iN1k1** [comment]
you problably have to compile the Regression tree lib for your machine architecture. The RT lib is in src/libs/RT

**Comment by Feesics** [comment]
Thank you for your reply and I have already did it as what you say. Now I am waitting for the result. Best regards to you!

**Comment by Feesics** [comment]
Error using ComputeDists (line 4)
Attempt to reference field of non-structure array.
The code occurred the above mistake just now, how can I solve it? Thanks.
